# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab68ecf75dcf440aa3ef6e2c1006c5aafbb57b5a39e546e1549c538a1f3c7066aa0490bfe6a845e80c830364fefc5c9ec4145afa7e64d649a36f46fe3ca827e

test:
  secret_key_base: f168403525f7165c6f520da417217ee8c7a3e2f016b50f96f136a4d2b502c559330dc386e5c5b9e9106f0adbc3d974e2839cf9a3f724a6e01f6181efbdac2b65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
